(() => {
  const page = document.body.dataset.page || 'app';
  const keys = { profile: 'timeguard_profile_v1', tasks: 'timeguard_tasks_v1', stats: 'timeguard_stats_v1' };
  const limits = { free: { perDay: 5, daysAhead: 3 }, plus: { perDay: 30, daysAhead: 14 }, team: { perDay: 100, daysAhead: 60 } };
  const $ = (id) => document.getElementById(id);
  const read = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } };
  const write = (key, value) => localStorage.setItem(key, JSON.stringify(value));
  const uid = () => Math.random().toString(16).slice(2) + Date.now().toString(16);
  const todayIso = () => new Date().toISOString().slice(0, 10);
  const toMinutes = (time) => { const [h, m] = String(time).split(':').map(Number); return h * 60 + m; };
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c]));
  let profile = read(keys.profile, null);
  let tasks = read(keys.tasks, []);
  let stats = read(keys.stats, { conflicts: 0, lastSubmitAt: 0 });
  let selectedDate = todayIso();
  function save() { write(keys.profile, profile); write(keys.tasks, tasks); write(keys.stats, stats); window.TimeGuardNav?.renderAuthNav?.(); }
  function plan() { return String(profile?.plan || 'free').toLowerCase(); }
  function planLimit() { return limits[plan()] || limits.free; }
  function toast(message) { const el = $('toast'); if (!el) return; el.textContent = message; el.classList.remove('hidden'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.add('hidden'), 2600); }
  function showAlert(message, type = 'bad') { const el = $('alertBox'); if (!el) return; el.textContent = message; el.className = `alert ${type}`; el.classList.remove('hidden'); }
  function hideAlert() { $('alertBox')?.classList.add('hidden'); }
  function tasksByDate(date) { return tasks.filter(t => t.date === date).sort((a, b) => toMinutes(a.start) - toMinutes(b.start) || priorityWeight(a.priority) - priorityWeight(b.priority)); }
  function priorityWeight(p) { return { high: 0, medium: 1, low: 2 }[p] ?? 1; }
  function isFutureLimitBlocked(date) { const start = new Date(todayIso()); const target = new Date(date); const diff = Math.round((target - start) / 86400000); return diff > planLimit().daysAhead; }
  function findConflict(candidate) { return tasksByDate(candidate.date).find(t => t.id !== candidate.id && toMinutes(candidate.start) < toMinutes(t.end) && toMinutes(candidate.end) > toMinutes(t.start)); }
  function renderProfile() { if ($('profileRoleBadge')) $('profileRoleBadge').textContent = profile?.role || 'guest'; if ($('planBadge')) $('planBadge').textContent = String(plan()).toUpperCase(); if ($('profileName')) $('profileName').value = profile?.name || ''; if ($('profileEmail')) $('profileEmail').value = profile?.email || ''; if ($('profileSummary') && profile) { $('profileSummary').textContent = `${profile.name || 'Пользователь'} · ${profile.email || 'email не указан'} · тариф ${String(profile.plan || 'free').toUpperCase()}`; $('profileSummary').classList.remove('hidden'); } }
  function renderStats() { if ($('tasksTodayCount')) $('tasksTodayCount').textContent = tasksByDate(selectedDate).length; if ($('conflictCount')) $('conflictCount').textContent = stats.conflicts || 0; if ($('daysCount')) $('daysCount').textContent = new Set(tasks.map(t => t.date)).size; }
  function renderTimeline() { const list = tasksByDate(selectedDate); if ($('taskDate')) $('taskDate').value = selectedDate; if ($('selectedDateTitle')) $('selectedDateTitle').textContent = `План на ${selectedDate}`; if ($('emptyState')) $('emptyState').classList.toggle('hidden', list.length > 0); if (!$('timeline')) return; $('timeline').innerHTML = list.map(task => `<article class="task ${task.done ? 'done' : ''}"><time>${task.start}–${task.end}</time><div><h3>${esc(task.title)}</h3><p>${esc(task.notes || 'Без комментария')}</p><span class="badge">${labelPriority(task.priority)}</span><span class="badge">${labelCategory(task.category)}</span></div><div class="actions"><button class="btn btn-ghost" data-done="${task.id}">${task.done ? 'Вернуть' : 'Готово'}</button><button class="btn btn-ghost" data-delete="${task.id}">Удалить</button></div></article>`).join(''); document.querySelectorAll('[data-done]').forEach(btn => btn.addEventListener('click', () => toggleDone(btn.dataset.done))); document.querySelectorAll('[data-delete]').forEach(btn => btn.addEventListener('click', () => deleteTask(btn.dataset.delete))); }
  function renderDayView() { const box = $('dayView'); if (!box) return; const list = tasksByDate(selectedDate); if ($('visualDateTitle')) $('visualDateTitle').textContent = `Расписание на ${selectedDate}`; const hours = Array.from({ length: 15 }, (_, i) => i + 8); box.innerHTML = hours.map(hour => { const start = hour * 60; const end = start + 60; const items = list.filter(task => toMinutes(task.start) >= start && toMinutes(task.start) < end); return `<div class="day-row"><div class="day-hour">${String(hour).padStart(2, '0')}:00</div><div class="day-events">${items.length ? items.map(task => `<div class="day-event ${task.priority || 'medium'} ${task.done ? 'done' : ''}"><small>${task.start}–${task.end} · ${labelPriority(task.priority)} · ${labelCategory(task.category)}</small><strong>${esc(task.title)}</strong></div>`).join('') : '<span class="day-empty-slot">Свободно</span>'}</div></div>`; }).join(''); }
  function labelPriority(p) { return { high: 'Высокий', medium: 'Средний', low: 'Низкий' }[p] || p; }
  function labelCategory(c) { return { study: 'Учёба', work: 'Работа', meeting: 'Встреча', personal: 'Личное', health: 'Здоровье' }[c] || c; }
  function renderAll() { renderProfile(); renderStats(); renderTimeline(); renderDayView(); }
  function toggleDone(id) { tasks = tasks.map(t => t.id === id ? { ...t, done: !t.done } : t); save(); renderAll(); }
  function deleteTask(id) { tasks = tasks.filter(t => t.id !== id); save(); renderAll(); toast('Задача удалена'); }
  function addTaskFromForm(event) { event.preventDefault(); hideAlert(); const now = Date.now(); if (now - Number(stats.lastSubmitAt || 0) < 2500) { showAlert('Слишком быстро. Подождите пару секунд перед повторным добавлением.'); return; } const task = { id: uid(), date: $('taskDate').value, title: $('taskTitle').value.trim(), start: $('taskStart').value, end: $('taskEnd').value, priority: $('taskPriority').value, category: $('taskCategory').value, notes: $('taskNotes').value.trim(), done: false, createdAt: new Date().toISOString() }; if (!$('robotCheck').checked) { showAlert('Поставьте отметку «Я не робот» перед сохранением.'); return; } if (!task.date || !task.title || !task.start || !task.end) { showAlert('Заполните дату, название, начало и окончание задачи.'); return; } if (toMinutes(task.end) <= toMinutes(task.start)) { showAlert('Окончание задачи должно быть позже начала.'); return; } if (isFutureLimitBlocked(task.date)) { openPaywall(); return; } if (tasksByDate(task.date).length >= planLimit().perDay) { openPaywall(); return; } const conflict = findConflict(task); if (conflict) { stats.conflicts = Number(stats.conflicts || 0) + 1; stats.lastSubmitAt = now; save(); renderStats(); showAlert(`Нельзя добавить задачу: она пересекается с «${conflict.title}» (${conflict.start}–${conflict.end}).`); return; } tasks.push(task); stats.lastSubmitAt = now; selectedDate = task.date; save(); event.target.reset(); $('taskDate').value = selectedDate; renderAll(); showAlert('Задача добавлена. План дня обновлён.', 'ok'); }
  function openPaywall() { $('paywallModal')?.classList.remove('hidden'); toast('Достигнут Free-лимит'); }
  function closePaywall() { $('paywallModal')?.classList.add('hidden'); }
  function shiftDate(days) { const d = new Date(selectedDate); d.setDate(d.getDate() + days); selectedDate = d.toISOString().slice(0, 10); renderAll(); }
  function fillDemo() { const date = todayIso(); const examples = [{ title: 'Разобрать проект', start: '10:00', end: '11:30', priority: 'high', category: 'study', notes: 'Подготовить структуру' }, { title: 'Рабочая встреча', start: '12:00', end: '13:00', priority: 'medium', category: 'meeting', notes: 'Обсудить задачи на день' }, { title: 'Тренировка', start: '18:30', end: '19:30', priority: 'low', category: 'health', notes: 'Не забыть форму' }]; tasks = tasks.filter(t => t.date !== date).concat(examples.map(item => ({ id: uid(), date, done: false, createdAt: new Date().toISOString(), ...item }))); selectedDate = date; save(); renderAll(); toast('Примерный день добавлен'); }
  function clearDay() { tasks = tasks.filter(t => t.date !== selectedDate); save(); renderAll(); toast('День очищен'); }
  function bindApp() { selectedDate = todayIso(); if ($('taskDate')) $('taskDate').value = selectedDate; $('profileForm')?.addEventListener('submit', (e) => { e.preventDefault(); profile = { name: $('profileName').value.trim() || 'Пользователь TimeGuard', email: $('profileEmail').value.trim() || 'user@example.com', role: profile?.role || 'user', plan: profile?.plan || 'free', createdAt: profile?.createdAt || new Date().toISOString() }; save(); renderAll(); toast('Профиль сохранён'); }); $('taskForm')?.addEventListener('submit', addTaskFromForm); $('fillDemoBtn')?.addEventListener('click', fillDemo); $('clearDayBtn')?.addEventListener('click', clearDay); $('prevDateBtn')?.addEventListener('click', () => shiftDate(-1)); $('nextDateBtn')?.addEventListener('click', () => shiftDate(1)); $('todayBtn')?.addEventListener('click', () => { selectedDate = todayIso(); renderAll(); }); $('closePaywallBtn')?.addEventListener('click', closePaywall); $('stayFreeBtn')?.addEventListener('click', closePaywall); }
  function cabinet() { const box = $('cabinetProfile'); if (box) box.textContent = profile ? `${profile.name} · ${profile.email}` : 'Профиль ещё не создан'; if ($('cabinetPlan')) $('cabinetPlan').textContent = String(plan()).toUpperCase(); const grouped = [...new Set(tasks.map(t => t.date))].sort(); $('cabinetEmpty')?.classList.toggle('hidden', grouped.length > 0); if ($('cabinetPlans')) $('cabinetPlans').innerHTML = grouped.map(date => `<article class="card small-card"><h3>${date}</h3><p>${tasksByDate(date).length} задач</p><p>${tasksByDate(date).filter(t => t.done).length} выполнено</p></article>`).join(''); }
  function pricing() { document.querySelectorAll('[data-plan]').forEach(btn => btn.addEventListener('click', () => { localStorage.setItem('timeguard_selected_plan', btn.dataset.plan); location.href = `payment-success.html?plan=${btn.dataset.plan}`; })); }
  function payment() { const params = new URLSearchParams(location.search); const newPlan = params.get('plan') || localStorage.getItem('timeguard_selected_plan') || 'plus'; if ($('activatedPlan')) $('activatedPlan').textContent = newPlan.toUpperCase(); $('activatePlanBtn')?.addEventListener('click', () => { profile = profile || { name: 'Пользователь TimeGuard', email: 'user@example.com', role: 'user' }; profile.plan = newPlan; save(); toast('Тариф активирован'); setTimeout(() => location.href = 'cabinet.html?v=12', 800); }); }
  function admin() { const allowed = profile?.role === 'admin'; $('adminDenied')?.classList.toggle('hidden', allowed); $('adminContent')?.classList.toggle('hidden', !allowed); if (allowed) { $('adminUsers').textContent = profile ? 1 : 0; $('adminTasks').textContent = tasks.length; $('adminDays').textContent = new Set(tasks.map(t => t.date)).size; $('adminDone').textContent = tasks.filter(t => t.done).length; } }
  if (page === 'app') { bindApp(); renderAll(); }
  if (page === 'cabinet') cabinet();
  if (page === 'pricing') pricing();
  if (page === 'payment') payment();
  if (page === 'admin') admin();
})();
